#!/usr/bin/env python3
"""
Refresh selected Data360 Beast evidence artifacts and specialist skills using only
the local sf-docs Help export.

This script is intentionally narrow and deterministic:
- Reads `docs/data360/help/summaries/*.json` (generated by export_sf_docs_cache.py)
- Rewrites only sections delimited by SF_DOC_SYNC markers in a small set of
  docs-side evidence artifacts and specialist SKILL.md files
- Does not invent endpoints/limits/permissions; it only summarizes cached official Help pages
- Keeps the top-level data360beast router lean; broad changelog gates belong in
  docs-side artifacts such as docs/proof-ledger.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
HELP_DIR = ROOT / "docs" / "data360" / "help"
SUMMARIES_DIR = HELP_DIR / "summaries"


@dataclass(frozen=True)
class HelpSummary:
    article_id: str
    title: str
    source: str
    extracted_at: str | None
    lead: str
    headings: list[str]
    bullets: list[str]


def load_summary(article_id: str) -> HelpSummary:
    path = SUMMARIES_DIR / f"{article_id.removesuffix('.htm')}.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    summary = payload.get("summary") or {}
    return HelpSummary(
        article_id=payload.get("articleId") or article_id,
        title=payload.get("title") or "",
        source=payload.get("source") or "",
        extracted_at=None,
        lead=(summary.get("lead") or "").strip(),
        headings=[h.strip() for h in (summary.get("headings") or []) if h.strip()],
        bullets=[b.strip() for b in (summary.get("bullets") or []) if b.strip()],
    )


def find_extracted_at_in_raw(article_id: str) -> str | None:
    raw_path = HELP_DIR / "raw" / f"{article_id.removesuffix('.htm')}.md"
    if not raw_path.exists():
        return None
    # Frontmatter line: extractedAt: "..."
    for line in raw_path.read_text(encoding="utf-8").splitlines()[:20]:
        if line.startswith("extractedAt:"):
            value = line.split(":", 1)[1].strip()
            return value.strip().strip('"')
    return None


def render_block(header: str, sources: Iterable[HelpSummary], bullets: list[str]) -> str:
    source_list = list(sources)
    src_lines = []
    for s in source_list:
        src_lines.append(f"- {s.article_id} — {s.title}")
    src_section = "\n".join(src_lines) if src_lines else "- (none)"
    bullet_section = "\n".join([f"- {b}" for b in bullets]) if bullets else "- (no extracted bullets)"
    fingerprint_input = "\n".join(
        [s.article_id + "|" + s.title + "|" + s.source + "|" + "|".join(s.headings + s.bullets) for s in source_list]
    )
    fingerprint = hashlib.sha256(fingerprint_input.encode("utf-8")).hexdigest()[:24]
    return "\n".join(
        [
            f"### {header}",
            "",
            "_Auto-synced from the local sf-docs cached Salesforce Help export (official docs only).",
            "",
            "**Sources (sf-docs cached Help):**",
            src_section,
            "",
            f"**Source fingerprint:** `{fingerprint}`",
            "",
            "**Notes:**",
            bullet_section,
            "",
        ]
    )


def replace_marked_section(text: str, key: str, replacement_markdown: str) -> str:
    start = f"<!-- SF_DOC_SYNC_START:{key} -->"
    end = f"<!-- SF_DOC_SYNC_END:{key} -->"
    if start in text and end in text:
        pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
        return pattern.sub(f"{start}\n{replacement_markdown}\n{end}", text, count=1)
    # Append a new section at the end with markers.
    suffix = "\n".join([start, replacement_markdown, end, ""])
    if not text.endswith("\n"):
        text += "\n"
    return text + "\n## Doc-Synced Notes\n\n" + suffix


def apply_doc_synced_blocks(text: str, blocks: dict[str, str]) -> str:
    updated = text
    for key, markdown in blocks.items():
        updated = replace_marked_section(updated, key, markdown)
    return updated


def render_limits_gate(label: str, source: HelpSummary, phase_notes: list[str]) -> str:
    headings = [
        heading
        for heading in source.headings
        if "Guidelines and Limits" in heading
    ]
    heading_text = ", ".join(headings[:12])
    bullets = [
        "Treat the captured Limits and Guidelines page as a required source before making durable guidance for this phase.",
        "Separate soft guidelines from hard limits, and call out when a limit can require an Account Executive request or org-specific validation.",
        *phase_notes,
    ]
    if heading_text:
        bullets.append(f"Relevant limit families currently captured include: {heading_text}.")
    return render_block(label, [source], bullets)


def render_changelog_gate(source: HelpSummary) -> str:
    recent = ", ".join(source.headings[:8])
    bullets = [
        "Check this changelog before treating older Beast guidance as durable; it tracks licensing, access, availability, billing, limits, and permission-set documentation changes.",
        "When a changelog entry touches a phase, update the owning specialist skill and any public-safe markdown map in the same run.",
    ]
    if recent:
        bullets.append(f"Most recent captured entry headings: {recent}.")
    return render_block("Usage and access changelog gate", [source], bullets)


def build_skill_updates() -> dict[Path, dict[str, str]]:
    """
    Returns { skill_path: { marker_key: replacement_markdown } }.
    """
    updates: dict[Path, dict[str, str]] = {}

    def add(skill_rel: str, key: str, md: str) -> None:
        skill_path = ROOT / skill_rel
        updates.setdefault(skill_path, {})[key] = md.rstrip() + "\n"

    # Data spaces + API usage
    s_data_spaces = load_summary("data.c360_a_data_spaces.htm")
    s_using_apis = load_summary("data.c360_a_using_data_cloud_apis_with_data_spaces.htm")
    add(
        "skills/sf-datacloud-governance/SKILL.md",
        "data-spaces",
        render_block(
            "Data Spaces (visibility boundary)",
            [s_data_spaces],
            [
                "Treat a data space as a logical partition; it scopes data, metadata, and processes for teams (brand/region/department).",
                "Data space assignment via permission sets controls what users can work on in that context; it is not the same thing as granting data access (policies still matter).",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-connectapi/SKILL.md",
        "data-spaces-api",
        render_block(
            "Data Spaces in API/Connector Usage (do not guess the mechanism)",
            [s_using_apis],
            [
                "Token exchange: include a body parameter named `dataspace` with the data space name to get a Data 360 token scoped to that data space.",
                "SQL clients: set a driver/user property named `dataspace` to query in a specific data space.",
                "Python connector: pass an additional connection parameter named `dataspace` with the data space name.",
                "Connect APIs: pass the data space name as an extra parameter (example shown in the Help page). Validate per-endpoint support in OpenAPI before assuming it exists everywhere.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-retrieve/SKILL.md",
        "data-spaces-retrieve",
        render_block(
            "Data Spaces in Query Tooling",
            [s_using_apis],
            [
                "If results differ by user or environment, confirm whether the query path is scoped by a data space (token exchange, connector property, or API extra parameter).",
                "Treat data space selection as part of proof: include the data space in readbacks and troubleshooting probes.",
            ],
        ),
    )

    # Permission sets + transition note (kept as a short operational reminder)
    s_perms = load_summary("data.c360_a_userpermissions.htm")
    add(
        "skills/sf-datacloud-governance/SKILL.md",
        "permission-sets",
        render_block(
            "Standard Permission Sets (operational reminders)",
            [s_perms],
            [
                "Standard Data 360 permission sets can change over time; avoid custom clones unless you have a specific reason and a review process.",
                "System Administrator profile can have broad data space definition access; validate governed runtime behavior with a non-admin user when proving policies.",
            ],
        ),
    )

    # Search index + retriever setup (high-level, avoids numeric limits unless explicitly included)
    s_search_ground = load_summary("sf.c360_a_search_index_ground_ai.htm")
    s_hybrid_create = load_summary("data.c360_a_hybridsearch_index_create.htm")
    s_retriever_create = load_summary("data.c360_a_ai_retriever_create.htm")
    add(
        "skills/sf-datacloud-unstructured-retrieval/SKILL.md",
        "search-index-and-retrievers",
        render_block(
            "Search Index + Retriever Setup (UI path)",
            [s_search_ground, s_hybrid_create, s_retriever_create],
            [
                "Hybrid search is intended to combine semantic (vector) and lexical (keyword) matching; choose it when vocabulary precision matters.",
                "Advanced Setup includes parser/preprocessing choices; some options are available only for certain file types and are mutually exclusive in specific combinations.",
                "Index configuration can include filter fields and ranking factors; retriever filters depend on filter fields being defined on the index.",
                "Creating an index can produce related objects (chunk/index DMOs); include them in governance and monitoring.",
                "Retriever configuration includes selecting the data space, DMO, index, optional filters, return fields, and (optional) citations; activate a version before use in prompts.",
            ],
        ),
    )

    s_limits = load_summary("data.c360_a_limits_and_guidelines.htm")
    s_changelog = load_summary("data.c360_a_changelog_usage_and_access.htm")
    add("docs/proof-ledger.md", "weekly-watch-gate", render_changelog_gate(s_changelog))
    add(
        "skills/sf-datacloud/SKILL.md",
        "limits-first-architecture",
        render_limits_gate(
            "Limits-first architecture gate",
            s_limits,
            [
                "For cross-phase designs, explicitly identify the phase that owns each limit: ingest, model, query, insights, segment, activation, automation, search, or API.",
                "Keep cost, throttling, hard limits, and feature availability in the proof plan, not as afterthoughts.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-prepare/SKILL.md",
        "limits-data-ingestion",
        render_limits_gate(
            "Data ingestion and transform limit gate",
            s_limits,
            [
                "Before recommending stream count, refresh cadence, file volume, transform shape, or retry behavior, check the captured ingestion and transform limit families.",
                "Prefer smaller probes and explicit readback when a design can affect metered ingestion, processing, or storage.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-harmonize/SKILL.md",
        "limits-modeling-identity-graphs",
        render_limits_gate(
            "Modeling, identity, and graph limit gate",
            s_limits,
            [
                "Before choosing DMO shape, relationship paths, identity rulesets, or Data Graph shape, check limits for DMOs, identity resolution, and Data Graphs.",
                "Escalate unclear relationship, key, or graph-volume assumptions into metadata probes instead of baking them into skill guidance.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-calculated-insights/SKILL.md",
        "limits-insights",
        render_limits_gate(
            "Calculated and streaming insight limit gate",
            s_limits,
            [
                "Before promoting CI SQL patterns, check calculated-insight, real-time insight, and streaming-insight limit families.",
                "Separate SQL validity from job/runtime proof; limits can apply after a query compiles.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-segment/SKILL.md",
        "limits-segmentation",
        render_limits_gate(
            "Segmentation limit gate",
            s_limits,
            [
                "Before recommending segment shape, publish cadence, counts, or DBT segment strategy, check the segmentation limit family and publish-related Help pages.",
                "Treat count success, publish success, and activation pickup as separate proof targets.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-act/SKILL.md",
        "limits-activation",
        render_limits_gate(
            "Activation limit gate",
            s_limits,
            [
                "Before recommending activation targets, DMO activation, API activation, or publish schedule, check activation and data-action limit families.",
                "Call out whether a target is internal, external, file-based, API-based, or event-driven because limits and proof differ.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-automation/SKILL.md",
        "limits-data-actions",
        render_limits_gate(
            "Data action and event limit gate",
            s_limits,
            [
                "Before recommending data actions, Flow delivery, webhook delivery, or event subscribers, check data-action limits and Platform Event delivery implications.",
                "Distinguish home-org platform delivery from external subscriber delivery when discussing allocation pressure.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-connectapi/SKILL.md",
        "limits-api",
        render_limits_gate(
            "API limit gate",
            s_limits,
            [
                "Before writing reusable API guidance, check the API Guidelines and Limits family and OpenAPI catalog together.",
                "Do not treat a method/path as production-ready until limits, data space mechanics, permissions, and readback proof are named.",
            ],
        ),
    )
    add(
        "skills/sf-datacloud-unstructured-retrieval/SKILL.md",
        "limits-unstructured-search",
        render_limits_gate(
            "Unstructured data and search index limit gate",
            s_limits,
            [
                "Before recommending chunking, parser mode, ranking fields, index refresh, or retriever shape, check the unstructured-data and search-index limit family.",
                "Keep reindexing, embedding, query, storage, and intelligent-processing cost in the design review.",
            ],
        ),
    )

    return updates


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Write changes to disk")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if changes would be made")
    args = parser.parse_args()

    updates = build_skill_updates()
    changed: list[Path] = []

    for path, blocks in updates.items():
        original = path.read_text(encoding="utf-8")
        updated = apply_doc_synced_blocks(original, blocks)
        if updated != original:
            changed.append(path)
            if args.apply:
                path.write_text(updated, encoding="utf-8")

    if changed:
        print("Docs/skill files updated:")
        for p in changed:
            print(f"- {p.relative_to(ROOT)}")
        if args.check and not args.apply:
            return 2
    else:
        print("No docs/skill updates needed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
